# Generated by Django 5.2.4 on 2025-07-12 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('whatsapp_number', models.CharField(max_length=12)),
                ('quantity', models.IntegerField()),
                ('message', models.TextField()),
                ('residence', models.CharField(choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo-marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa-bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', 'Muranga'), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandara', 'Nyandara'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Sayaya'), ('taita-taveta', 'Taita Taveta'), ('tana-river', 'Tana River'), ('tharaka-nithi', 'Tharaka Nithi'), ('trans-nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin-gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west-pokot', 'West Pokot')], max_length=50)),
                ('pastry', models.CharField(choices=[('biscuits', 'Biscuits'), ('bread', 'Bread'), ('brownies', 'Brownies'), ('cake', 'Cake'), ('cinnamon-rolls', 'Cinnamon Rolls'), ('cookies', 'Cookies'), ('cupcakes', 'Cupcakes'), ('donuts', 'Donuts'), ('muffins', 'Muffins'), ('pies', 'Pies'), ('samosas', 'Samosas'), ('scones', 'Scones'), ('mandazi', 'Mandazi'), ('croissants', 'Croissants')], max_length=50)),
                ('occasion', models.CharField(choices=[('anniversary', 'Anniversary'), ('baby-shower', 'Baby Shower'), ('birthday', 'Birthday'), ('farewell-pary', 'Farewell Party'), ('gender-reveal', 'Gender Reveal'), ('housewarming', 'Housewarming'), ('promotion', 'Promotion'), ('retirement-party', 'Retirement Party'), ('wedding', 'Wedding')], max_length=50)),
                ('flavours', models.CharField(choices=[('none', 'None'), ('almond-cake', 'Almond Cake'), ('apple-cinnamon', 'Apple Cinnamon'), ('banana', 'Banana'), ('black-forest', 'Black Forest'), ('blueberry', 'Blueberry'), ('butter-cake', 'Butter Cake'), ('caramel', 'Caramel'), ('cheese-layered-cake', 'Cheese Layered Cake'), ('chocolate', 'Chocolate'), ('chocolate-fudge', 'Chocolate Fudge'), ('coconut-cake', 'Coconut Cake'), ('lemon', 'Lemon'), ('lemon-vanilla', 'Lemon Vanilla'), ('mango', 'Mango'), ('marble', 'Marble'), ('mixed-fruit', 'Mixed Fruit'), ('mocha', 'Mocha'), ('nutella', 'Nutella'), ('nutty-carrot-cake', 'Nutty Carrot Cake'), ('orange', 'Orange'), ('oreo', 'Oreo'), ('passion', 'Passion'), ('pecan-praline', 'Pecan Praline'), ('pineapple', 'Pineapple'), ('plain-carrot-cake', 'Plain Carrot Cake'), ('red-velvet', 'Red Velvet'), ('sponge-cake', 'Sponge Cake'), ('spice-cake', 'Spice Cake'), ('strawberry', 'Strawberry'), ('vanilla', 'Vanilla'), ('walnut-cake', 'Walnut Cake'), ('white-forest', 'White Forest'), ('other', 'Other')], max_length=50)),
                ('measurement', models.CharField(choices=[('kgs', 'Kgs'), ('pieces', 'Pieces')], max_length=6)),
            ],
        ),
    ]
