# Generated by Django 5.2.4 on 2025-07-12 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_orderhere'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderhere',
            old_name='flavours',
            new_name='flavour',
        ),
    ]
