# Generated by Django 5.2.4 on 2026-01-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_rename_flavours_orderhere_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhere',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderhere',
            name='occasion',
            field=models.CharField(choices=[('anniversary', 'Anniversary'), ('baby-shower', 'Baby Shower'), ('birthday', 'Birthday'), ('farewell-party', 'Farewell Party'), ('gender-reveal', 'Gender Reveal'), ('housewarming', 'Housewarming'), ('promotion', 'Promotion'), ('retirement-party', 'Retirement Party'), ('wedding', 'Wedding')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhere',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orderhere',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='orderhere',
            name='residence',
            field=models.CharField(choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo-marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa-bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('muranga', 'Muranga'), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita-taveta', 'Taita Taveta'), ('tana-river', 'Tana River'), ('tharaka-nithi', 'Tharaka Nithi'), ('trans-nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin-gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west-pokot', 'West Pokot')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderhere',
            name='whatsapp_number',
            field=models.CharField(max_length=15),
        ),
    ]
