# Generated by Django 5.2.4 on 2026-01-10 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_orderhere_created_at_alter_orderhere_occasion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhere',
            name='flavour',
            field=models.CharField(choices=[('almond-cake', 'Almond Cake'), ('apple-cinnamon', 'Apple Cinnamon'), ('banana', 'Banana'), ('black-forest', 'Black Forest'), ('blueberry', 'Blueberry'), ('butter-cake', 'Butter Cake'), ('caramel', 'Caramel'), ('cheese-layered-cake', 'Cheese Layered Cake'), ('chocolate', 'Chocolate'), ('chocolate-fudge', 'Chocolate Fudge'), ('coconut-cake', 'Coconut Cake'), ('lemon', 'Lemon'), ('lemon-vanilla', 'Lemon Vanilla'), ('mango', 'Mango'), ('marble', 'Marble'), ('mixed-fruit', 'Mixed Fruit'), ('mocha', 'Mocha'), ('nutella', 'Nutella'), ('nutty-carrot-cake', 'Nutty Carrot Cake'), ('orange', 'Orange'), ('oreo', 'Oreo'), ('passion', 'Passion'), ('pecan-praline', 'Pecan Praline'), ('pineapple', 'Pineapple'), ('plain-carrot-cake', 'Plain Carrot Cake'), ('red-velvet', 'Red Velvet'), ('sponge-cake', 'Sponge Cake'), ('spice-cake', 'Spice Cake'), ('strawberry', 'Strawberry'), ('vanilla', 'Vanilla'), ('walnut-cake', 'Walnut Cake'), ('white-forest', 'White Forest'), ('other', 'Other')], max_length=50),
        ),
    ]
