# Generated by Django 5.2.4 on 2026-06-15 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_alter_orderhere_flavour'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderhere',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
